wget https://www.kellogg.northwestern.edu/images/students/all/aam089.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/dta949.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/abb913.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/obt8574.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/mmb0775.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/tbt439.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/aeb229.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/rbu4871.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/rab2387.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/ejc604.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/akf870.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/gcf2179.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/igj097.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/agz567.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/mbg556.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/fgh963.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/kgq463.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/llh483.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/slh973.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/tmj390.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/mtk346.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/mhl499.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/aam2206.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/kmy025.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/jem112.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/trm890.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/hhm4360.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/rno7213.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/anz664.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/jeo6296.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/blp2722.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/asz369.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/elt557.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/gwt4106.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/mtl5731.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/mur077.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/due060.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/nvb540.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/asw753.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/stw907.jpgwget 